;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;
;;	    ____        __      __              
;;	   / __ \____  / /_  __/ /_  ____ ______
;;	  / /_/ / __ \/ / / / / __ \/ __ `/ ___/
;;	 / ____/ /_/ / / /_/ / /_/ / /_/ / /    
;;	/_/    \____/_/\__, /_.___/\__,_/_/     
;;	              /____/                    
;;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

;; ==========================================================
;; 🎨 DEFINICIÓN DE COLORES
;; ==========================================================
[color]
bg = #00000000
fg = #c0caf5
;; He cambiado 'blue' por un Cian mucho más potente
blue = #00ffff
;; He añadido un verde HTB más vivo
green = #a6e22e
red = #ff5555
gray = #717c9b
white = #ffffff
cyan = #7dcfff
yellow = #e0af68
orange = #ff9e64
purple = #bb9af7

;; ==========================================================
;; 🖥️ BARRA PRINCIPAL (Efecto Flotante)
;; ==========================================================
[bar/main]
width = 100%
height = 34
offset-x = 0
offset-y = 0
bottom = false
fixed-center = true

; FONDO TRANSPARENTE PARA CREAR LAS ISLAS
background = #00000000
foreground = ${color.fg}

; Bordes invisibles para empujar la barra hacia abajo
border-top-size = 0
border-bottom-size = 0
border-color = #00000000

; Optimización de Pantalla Completa (bspwm)
override-redirect = false
wm-restack = bspwm

; FUENTES (Hack + Iosevka)
font-0 = "Hack Nerd Font:size=11;3"
font-1 = "Hack Nerd Font:style=Bold:size=11;3"
font-2 = "Hack Nerd Font:size=15;4"
font-3 = "Iosevka Nerd Font:size=12;3"

; ORDEN DE LAS ISLAS
modules-left = sep_island network_island sep_island vpn_island
modules-center = bspwm
modules-right = target_island sep_island eth_island bluetooth_island sep_island wifi_island sep_island battery_island sep_island sysmenu
;Fuerza a Polybar a no dibujar nada debajo de ella
pseudo-transparency = false
compositing-background = source

;; ==========================================================
;; 🧩 MÓDULOS GLOBALES / SEPARADORES
;; ==========================================================
[module/sep_island]
type = custom/text
content = ""
content-background = #00000000
content-foreground = #00000000

[module/sysmenu]
type = custom/text
content = "  "
content-background = ${color.bg-alt}
content-foreground = ${color.red}
content-padding = 1
click-left = ~/.config/bspwm/scripts/powermenu.sh &

;; ==========================================================
;; ⬅️ ZONA IZQUIERDA: RED Y VPN (Scripts Inteligentes)
;; ==========================================================
[module/network_island]
type = custom/script
exec = ~/.config/bspwm/scripts/network_island.sh
interval = 3
format = <label>
format-background = ${color.bg-alt}
format-padding = 2
click-left = kitty -e nmtui &

[module/vpn_island]
type = custom/script
exec = ~/.config/bspwm/scripts/vpn_island.sh
interval = 3
format = <label>
format-background = ${color.bg-alt}
format-padding = 2
click-right = sudo killall openvpn
click-left = kitty -e sudo openvpn /home/dnk29/ovpn/dnk29.ovpn &

;; ==========================================================
;; ⏺️ ZONA CENTRAL: ESPACIOS DE TRABAJO (bspwm)
;; ==========================================================
[module/bspwm]
type = internal/bspwm
format = <label-state>
format-background = ${color.bg-alt}
format-padding = 2

label-focused = "  "
label-focused-foreground = ${color.green}

label-occupied = "  "
label-occupied-foreground = ${color.fg}

label-urgent = "  "
label-urgent-foreground = ${color.red}

label-empty = "  "
label-empty-foreground = ${color.gray}

;; ==========================================================
;; ➡️ ZONA DERECHA: STATUS (Minimalista)
;; ==========================================================
[module/wifi_island]
type = internal/network
interface = wlan0
interval = 3.0

format-connected = <ramp-signal>
format-connected-background = ${color.bg-alt}
format-connected-padding = 2

ramp-signal-0 = %{F#f7768e}󰤯%{F-}
ramp-signal-1 = %{F#e0af68}󰤟%{F-}
ramp-signal-2 = %{F#e0af68}󰤢%{F-}
ramp-signal-3 = %{F#9ece6a}󰤥%{F-}
ramp-signal-4 = %{F#9ece6a}󰤨%{F-}

format-disconnected = <label-disconnected>
format-disconnected-background = ${color.bg-alt}
format-disconnected-padding = 2
label-disconnected = "%{F#f7768e}󰤮%{F-}"

[module/eth_island]
type = internal/network
interface = enp3s0
interval = 3.0

format-connected = "%{F#9ece6a}󰈀%{F-}"
format-connected-background = ${color.bg-alt}
format-connected-padding = 2
format-disconnected = ""

[module/bluetooth_island]
type = custom/script
exec = ~/.config/bspwm/scripts/bluetooth.sh
interval = 5
format-background = ${color.bg-alt}
format-padding = 2

[module/battery_island]
type = internal/battery
battery = BAT0
adapter = ADP1
full-at = 98

format-charging = <animation-charging> <label-charging>
format-charging-background = ${color.bg-alt}
format-charging-padding = 2

format-discharging = <ramp-capacity> <label-discharging>
format-discharging-background = ${color.bg-alt}
format-discharging-padding = 2

label-charging = %percentage%%
label-discharging = %percentage%%

ramp-capacity-0 = "%{F#f7768e} %{F-}"
ramp-capacity-1 = " "
ramp-capacity-2 = " "
ramp-capacity-3 = " "
ramp-capacity-4 = "%{F#9ece6a} %{F-}"

animation-charging-0 = " "
animation-charging-1 = " "
animation-charging-2 = " "
animation-charging-framerate = 750

[module/target_island]
type = custom/script
exec = ~/.config/bspwm/scripts/target_to_hack.sh
interval = 2
format-background = ${color.bg-alt}
format-padding = 2
; Al hacer click, borra el target directamente
click-left = echo '' > /home/dnk29/.config/bin/target

[settings]
screenchange-reload = true
